### ISSUE TITLE
Latest version pop up keeps appearing

### ISSUE THREAD

**Issue by tymorrow** [iig-uni-freiburg/WOLFGANG#1]
I have the latest release downloaded but a pop up is still appearing telling me that a newer version is available.

**Comment by adlange** [comment]
Hello @tymorrow, thanks for reporting this bug. Unfortunately I couldn't recreate it on my system.

May I ask you for which operating system you downloaded our Petri net editor?

_edit:_
As a first countermeasure you could deactivate the update check in the settings menu.

**Comment by adlange** [comment]
We fixed a bug in the uploaded Apple Disk Image. Hopefully it will work for you now, too.

Cheers, Adrian
